version: '3.8'

services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
      - ./web-root:/var/www/html
    command: certonly --webroot --email spatak90@gmail.com --agree-tos --no-eff-email --staging -d delivt.com  -d www.delivt.com -v
